name: Lint

on:
  workflow_dispatch:  # 改为手动触发

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: psf/black@stable
        with:
          options: "--check --verbose"
